Todo/Controllers/DeviceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Todo.Controllers.Base;
using Todo.Data;
using Todo.Model;
using Todo.Utility;

namespace Todo.Controllers
{
    public class DeviceController : TodoController<Model.User>
    {
        TodoUow Uow { get; set; }

        public DeviceController()
        {
            Uow = new TodoUow();
        }
        #region View
        public ActionResult Index()
        {
            return View();
        }

        #endregion

        #region Api
        [HttpGet]
        public ContentResult All()
        {
            var devices = Uow.Devices.AllActiveOrInactive().ToList();
            return JsonContent(devices);
        }

        [HttpGet]
        public ActionResult Get(long id)
        {
            var entity = Uow.Devices.Single(id);
            return JsonContent(entity);
        }

        [HttpPost]
        public ActionResult Post(Device entity)
        {
            entity.AddedBy = GetLogOnSessionModel().Id;
            entity.AddedDateTime = DateTime.Now;
            Uow.Devices.Add(entity);
            Uow.Commit();
            return JsonContent(entity);
        }

        [HttpPost]
        public ActionResult Put(Device entity)
        {
            var aEntity = Uow.Devices.Single(entity.Id);
            aEntity.Name = entity.Name;
            aEntity.Description = entity.Description;
            aEntity.Status = entity.Status;
            aEntity.UpdatedBy = GetLogOnSessionModel().Id;
            aEntity.UpdatedDateTime = DateTime.Now;
            Uow.Devices.Update(aEntity);
            Uow.Commit();
            return JsonContent(aEntity);
        }

        [HttpPost]
        public ActionResult Delete(long id)
        {
            var entity = Uow.Devices.Single(id);
            entity.UpdatedBy = GetLogOnSessionModel().Id;
            entity.UpdatedDateTime = DateTime.Now;
            Uow.Devices.Delete(entity);
            Uow.Commit();
            return JsonContent(entity);
        }
        #endregion
    }
}

Todo/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Todo.Controllers.Base;
using Todo.Data;
using Todo.Model;

namespace Todo.Controllers
{
    public class EventController : TodoController<Model.User>
    {
        TodoUow Uow { get; set; }

        public EventController()
        {
            Uow = new TodoUow();
        }

        #region View
        public ActionResult Index()
        {
            return View();
        }

        #endregion

        #region Api
        [HttpGet]
        public ContentResult All()
        {
            var events = Uow.Events.AllActiveOrInactive().Include(x => x.Device).ToList();
            return JsonContent(events);
        }

        [HttpGet]
        public ActionResult Get(long id)
        {
            var entity = Uow.Events.Single(id);
            return JsonContent(entity);
        }

        [HttpPost]
        public ActionResult Post(Event entity)
        {
            entity.AddedBy = GetLogOnSessionModel().Id;
            entity.AddedDateTime = DateTime.Now;
            Uow.Events.Add(entity);
            Uow.Commit();
            return JsonContent(entity);
        }

        [HttpPost]
        public ActionResult Put(Event entity)
        {
            var aEntity = Uow.Events.Single(entity.Id);
            aEntity.Name = entity.Name;
            aEntity.DeviceId = entity.DeviceId;
            aEntity.Description = entity.Description;
            aEntity.Status = entity.Status;
            aEntity.UpdatedBy = GetLogOnSessionModel().Id;
            aEntity.UpdatedDateTime = DateTime.Now;
            Uow.Events.Update(aEntity);
            Uow.Commit();
            return JsonContent(aEntity);
        }

        [HttpPost]
        public ActionResult Delete(long id)
        {
            var entity = Uow.Events.Single(id);
            entity.UpdatedBy = GetLogOnSessionModel().Id;
            entity.UpdatedDateTime = DateTime.Now;
            Uow.Events.Delete(entity);
            Uow.Commit();
            return JsonContent(entity);
        }
        #endregion
    }
}

Todo/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Providers.Entities;
using Todo.Controllers.Base;
using Todo.Data;
using Todo.Utility;

namespace Todo.Controllers
{
    public class LoginController : TodoController<Model.User>
    {
        TodoUow Uow { get; set; }

        public LoginController()
        {
            Uow = new TodoUow();
        }

        #region View
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Logout()
        {
            AbandonSession();
            return View("Index");
        }
        #endregion

        #region Api
        [HttpPost]
        public ContentResult Login(Model.User entity)
        {
            bool hasLogin = false;

            entity.Password = PasswordUtility.Encode(entity.Password);
            Model.User user = Uow.Users.All().FirstOrDefault(x => x.Email == entity.Email && x.Password == entity.Password);
            if (user != null)
            {
                SetLogOnSessionModel(user);
                hasLogin = true;
            }

            return JsonContent(hasLogin);
        }
        #endregion
    }
}

Todo/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Todo.Controllers.Base;
using Todo.Data;
using Todo.Utility;

namespace Todo.Controllers
{
    public class UserController : TodoController<Model.User>
    {

        TodoUow Uow { get; set; }

        public UserController()
        {
            Uow = new TodoUow();
        }

        #region View
        public ActionResult Index()
        {
            return View();
        }

        #endregion

        #region Api
        [HttpGet]
        public ContentResult All()
        {
            var users = Uow.Users.AllActiveOrInactive().ToList();
            return JsonContent(users);
        }

        [HttpGet]
        public ActionResult Get(long id)
        {
            var entity = Uow.Users.Single(id);
            return JsonContent(entity);
        }

        [HttpPost]
        public ActionResult Post(Model.User entity)
        {
            entity.Password = PasswordUtility.Encode(entity.Password);
            entity.AddedBy = GetLogOnSessionModel().Id;
            entity.AddedDateTime = DateTime.Now;
            Uow.Users.Add(entity);
            Uow.Commit();
            return JsonContent(entity);
        }

        [HttpPost]
        public ActionResult Put(Model.User entity)
        {
            var aEntity = Uow.Users.Single(entity.Id);

            aEntity.Name = entity.Name;
            aEntity.ContactNo = entity.ContactNo;
            aEntity.Email = entity.Email;
            aEntity.Password = (String.IsNullOrEmpty(entity.Password))
                ? aEntity.Password
                : PasswordUtility.Encode(entity.Password);
            aEntity.Status = entity.Status;
            aEntity.UpdatedBy = GetLogOnSessionModel().Id;
            aEntity.UpdatedDateTime = DateTime.Now;
            Uow.Users.Update(aEntity);
            Uow.Commit();
            return JsonContent(aEntity);
        }

        [HttpPost]
        public ActionResult Delete(long id)
        {
            var entity = Uow.Users.Single(id);
            entity.UpdatedBy = GetLogOnSessionModel().Id;
            entity.UpdatedDateTime = DateTime.Now;
            Uow.Users.Delete(entity);
            Uow.Commit();
            return JsonContent(entity);
        }
        #endregion

    }
}

Todo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <title>todo | @ViewBag.Title</title>
        <meta name="description"
              content="app, web app, responsive, admin dashboard, admin, flat, flat ui, ui kit, off screen nav"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>

        <link rel="stylesheet" href="~/Content/bootstrap.css" type="text/css"/>
        <link rel="stylesheet" href="~/Content/font-awesome.css" type="text/css"/>
        <link rel="stylesheet" href="~/Content/toastr.css" type="text/css"/>
        <link rel="stylesheet" href="~/Content/app.v1.css" type="text/css"/>
        <link href="~/Content/bootstrap-datepicker.css" rel="stylesheet" />
        <link href="~/Content/bootstrap-timepicker.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/Content/fullcalendar.min.css" />
        <link rel="stylesheet" href="~/Content/fullcalendar.print.css" media='print' />
        <link href="~/Content/site.css" rel="stylesheet" />
        @RenderSection("styles", false)

    </head>
    <body>
        @RenderSection("modals", false)
        <section class="hbox stretch"> <!-- .aside -->
            <aside class="bg-success dk aside-sm nav-vertical no-borders" id="nav">
                <section class="vbox">
                    <header class="nav-bar"><a class="btn btn-link visible-xs" data-toggle="class:nav-off-screen"
                                               data-target="body"> <i class="icon-reorder"></i> </a> <a href="@Url.Action("Index", "Schedule")"
                                                                                                        class="nav-brand"
                                                                                                        data-toggle="fullscreen">todo</a>
                        <a class="btn btn-link visible-xs" data-toggle="class:show" data-target=".nav-user"> <i
                                                                                                                 class="icon-comment-alt"></i> </a></header>
                    <footer class="footer bg-gradient hidden-xs">
                        <a href="@Url.Action("Logout", "Login")" class="btn btn-sm btn-link m-r-n-xs pull-right"> <i class="icon-off"></i> </a>
                        <a href="#nav" data-toggle="class:nav-vertical" class="btn btn-sm btn-link m-l-n-sm"> <i class="icon-reorder"></i></a>
                    </footer>
                    <section>
                        <div class="nav-user hidden-xs pos-rlt">
                            <div class="nav-avatar pos-rlt"><a href="#" class="thumb-sm avatar animated rollIn"
                                                               data-toggle="dropdown"> <img src="~/Content/images/avatar.jpg" alt=""
                                                                                            class=""> <span
                                                                                                          class="caret caret-white"></span> </a>
                                <ul class="dropdown-menu m-t-sm animated fadeInLeft">
                                    <span class="arrow top"></span>
                                    <li><a href="#">Settings</a></li>
                                    <li><a href="#">Profile</a></li>
                                    <li class="divider"></li>
                                    <li><a href="@Url.Action("Logout", "Login")">Logout</a></li>
                                </ul>
                            </div>
                        </div>
                        <nav class="nav-primary hidden-xs">
                            <ul id="navMenus" class="nav">
                                <li><a href="@Url.Action("Index", "User")"> <i class="icon-eye-open"></i> <span>User </span> </a></li>
                                <li><a href="@Url.Action("Index", "Device")"> <i class="icon-tasks"></i> <span>Device </span> </a></li>
                                <li><a href="@Url.Action("Index", "Event")"> <i class="icon-pencil"></i> <span>Event </span> </a></li>
                                <li><a href="@Url.Action("Index", "Schedule")"> <i class="icon-time"></i> <span>Schedule </span> </a></li>
                            </ul>
                        </nav>
                    </section>
                </section>
            </aside>
            <!-- /.aside --> 
            <!-- .vbox -->
            <section id="content">
                @RenderBody()
            </section>
            <!-- /.vbox -->
        </section>
        <script src="~/Scripts/jquery-2.1.1.js"></script>
        <script src="~/Scripts/json2.js"></script>
        <script src="~/Scripts/moment.js"></script>
        <script src="~/Scripts/amplify.js"></script>
        
        <script src="~/Scripts/bootstrap.js"></script>  
        <script src="~/Scripts/holder.js"></script>
        <script src="~/Scripts/jquery.blockUI.js"></script>
        <script src="~/Scripts/spin.js"></script>
        <script src="~/Scripts/bootbox.js"></script>
        <script src="~/Scripts/toastr.js"></script>

        <script src="~/Scripts/jquery-ui.custom.min.js"></script>
        <script src="~/Scripts/fullcalendar.min.js"></script>


        <script src="~/Scripts/knockout-3.2.0.js"></script>
        <script src="~/Scripts/knockout.validation.js"></script>
        <script src="~/Scripts/extensions/ko.bootstrapModal.js"></script>
        <script src="~/Scripts/extensions/ko.spinning.js"></script>
        
        <script src="~/Scripts/extensions/ko.bootstrapDatetimePicker.js"></script>
        <script src="~/Scripts/bootstrap-datepicker.js"></script>
        <script src="~/Scripts/bootstrap-timepicker.js"></script>

        @RenderSection("scripts", false)
    </body>
</html>